### ISSUE TITLE
Missing option for adding Organisation

### ISSUE THREAD

**Issue by Dryocopus** [OpenSILEX/opensilexClientToolsPython#3]
The Swagger editor interface suggests that it is possible to add an Organisation via the API:

![image](https://user-images.githubusercontent.com/60786510/124455520-fa07b800-dd89-11eb-86e1-c8093c3d090a.png)

However, the openSilexClientTools have no such entry in the OrganisationsAPI. Also there is no _dto-model for an organisation.

It is not the most important issue, because there will be just one organization-instance in the whole database, and it can be filled via the web-interface, but it raises questions about consistency.

Also, via our own application, I'm trying to build an option for doing a full initial load in a new environment based on JSON-files. Then it is handy to be able to load everything in one go.

**Comment by Isabelle-inrae** [comment]
Hi Peter,
I understand that you are confused on this point! The Organisation section was originally entitled Infrastructure.
We renamed it because Organisation was more in line with reality, but we haven't had time to refactor the code yet.
If you look for Infrastructure in the openSilexClientTools and the dto-model you should find everything you need.
Sorry for this confusing part!

Isabelle

**Comment by Dryocopus** [comment]
Ok, that works. Thanks.
